"""Loopback-only HTTPS fixture. Certificates are generated by CI, never committed."""
import http.server
import ssl

server = http.server.ThreadingHTTPServer(("127.0.0.1", 8443), http.server.SimpleHTTPRequestHandler)
context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
context.load_cert_chain("/tmp/malguard-test.crt", "/tmp/malguard-test.key")
server.socket = context.wrap_socket(server.socket, server_side=True)
server.serve_forever()
