const $=x=>document.getElementById(x);let file=null;
const SANDBOX_URL="https://malguard-core-sandbox.vercel.app/api/cloud-sandbox-self-test";
const cfg=()=>JSON.parse(localStorage.getItem("mgCfg")||'{"saveHistory":true,"mode":"standard"}');
function saveCfg(c){localStorage.setItem("mgCfg",JSON.stringify(c))}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("on"));$(b.dataset.page).classList.add("active");b.classList.add("on");if(b.dataset.page==="history")renderHistory()});
function sync(){let c=cfg();$("saveHistory").checked=c.saveHistory;$("scanMode").value=c.mode||"standard";$("guardMode").value=c.mode||"standard";$("homeMode").value=c.mode||"standard"}sync();
$("saveHistory").onchange=()=>{let c=cfg();c.saveHistory=$("saveHistory").checked;saveCfg(c)};
["scanMode","guardMode","homeMode"].forEach(id=>$(id).onchange=()=>{let c=cfg();c.mode=$(id).value;saveCfg(c);sync()});
$("resetSettings").onclick=()=>{localStorage.removeItem("mgCfg");sync()};
$("file").onchange=e=>{file=e.target.files?.[0]||null;$("pick").textContent=file?file.name:"Choose a file";$("scan").disabled=!file;$("result").hidden=true};
function magic(b){let h=[...b.slice(0,8)].map(x=>x.toString(16).padStart(2,"0")).join("");if(h.startsWith("4d5a"))return"Windows PE";if(h.startsWith("504b0304"))return"ZIP-compatible archive";if(h.startsWith("25504446"))return"PDF document";if(h.startsWith("89504e470d0a1a0a"))return"PNG image";if(h.startsWith("ffd8ff"))return"JPEG image";return"General / unrecognized file";}
async function hashFile(file){let buf=await file.arrayBuffer(),d=await crypto.subtle.digest("SHA-256",buf);return{buf,hash:[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}}
async function sandboxSelfTest(){let state=$("sandboxState"),btn=$("sandboxTest");btn.disabled=true;state.textContent="Starting isolated cloud self-test…";try{let r=await fetch(SANDBOX_URL,{method:"GET",cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"sandbox unavailable");state.textContent="PASS · ephemeral isolation · network "+j.isolation.networkPolicy+" · fixture SHA-256 "+j.report.sha256.slice(0,16)+"…";state.className="muted good";return j}catch(e){state.textContent="Cloud Sandbox self-test unavailable · "+e.message;state.className="muted bad";throw e}finally{btn.disabled=false}}
$("sandboxTest").onclick=()=>sandboxSelfTest().catch(()=>{});
$("scan").onclick=async()=>{if(!file)return;if(file.size>32*1024*1024){alert("Current iPhone preview limit: 32 MB.");return}let c=cfg(),mode=c.mode||"standard";$("scan").disabled=true;$("scan").textContent=mode==="sandbox"?"VERIFYING SANDBOX…":"SCANNING…";try{let {buf,hash}=await hashFile(file),b=new Uint8Array(buf),t=magic(b),s=[];if(mode==="plus"||mode==="pro")if(file.size<16)s.push("very small file");if(mode==="pro"&&t.includes("unrecognized"))s.push("unknown file signature");if(mode==="sandbox"){await sandboxSelfTest();s.push("Cloud isolation verified with MalGuard safe fixture");s.push("User file was NOT executed; arbitrary-file detonation remains fail-closed until containment upload path is certified")}if(!s.length)s.push("no "+mode+" local structural anomaly found");let v=s.some(x=>/unknown|anomaly/i.test(x))?"INCONCLUSIVE":"INCONCLUSIVE";$("name").textContent=file.name+" • "+file.size.toLocaleString()+" bytes";$("hash").textContent=hash;$("type").textContent=t;$("signals").textContent=s.join(" • ");$("verdict").textContent=v;$("result").hidden=false;if(c.saveHistory){let h=JSON.parse(localStorage.getItem("mgHistory")||"[]");h.unshift({name:file.name,hash,verdict:v,mode,time:new Date().toISOString()});localStorage.setItem("mgHistory",JSON.stringify(h.slice(0,30)))}}catch(e){$("signals").textContent="Scan stopped safely: "+e.message;$("verdict").textContent="STOPPED";$("result").hidden=false}finally{$("scan").disabled=false;$("scan").textContent="SCAN FILE"}};
function renderHistory(){let h=JSON.parse(localStorage.getItem("mgHistory")||"[]");$("historyList").innerHTML=h.length?h.map(x=>'<div class="item"><b>'+esc(x.name)+'</b><div class="muted">'+new Date(x.time).toLocaleString()+' · '+esc(x.mode||"standard")+'</div><div>'+esc(x.verdict)+'</div><div class="muted">'+esc(x.hash.slice(0,18))+'…</div></div>').join(""):'<p class="muted">No scans saved yet.</p>'}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
$("clearHistory").onclick=()=>{localStorage.removeItem("mgHistory");renderHistory()};
